/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Escrow {
      
    export type EscrowTransactionStruct = {buyer: AddressLike, seller: AddressLike, amount: BigNumberish, timestamp: BigNumberish, status: BigNumberish, evidenceHash: string, aiVerdict: string}

    export type EscrowTransactionStructOutput = [buyer: string, seller: string, amount: bigint, timestamp: bigint, status: bigint, evidenceHash: string, aiVerdict: string] & {buyer: string, seller: string, amount: bigint, timestamp: bigint, status: bigint, evidenceHash: string, aiVerdict: string }
  
    }

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "createEscrow" | "dispute" | "escrowCounter" | "escrows" | "getEscrowDetails" | "refundFunds" | "releaseFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowCreated" | "EscrowDisputed" | "EscrowRefunded" | "EscrowReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'dispute', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'escrowCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEscrowDetails', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundFunds', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'releaseFunds', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
  }

  
    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowDisputedEvent {
      export type InputTuple = [escrowId: BigNumberish, evidenceHash: string];
      export type OutputTuple = [escrowId: bigint, evidenceHash: string];
      export interface OutputObject {escrowId: bigint, evidenceHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowRefundedEvent {
      export type InputTuple = [escrowId: BigNumberish, aiVerdict: string];
      export type OutputTuple = [escrowId: bigint, aiVerdict: string];
      export interface OutputObject {escrowId: bigint, aiVerdict: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [escrowId: BigNumberish, aiVerdict: string];
      export type OutputTuple = [escrowId: bigint, aiVerdict: string];
      export interface OutputObject {escrowId: bigint, aiVerdict: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEscrow: TypedContractMethod<
      [_seller: AddressLike, ],
      [bigint],
      'payable'
    >
    

    
    dispute: TypedContractMethod<
      [_escrowId: BigNumberish, _evidenceHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    escrowCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, string, string] & {buyer: string, seller: string, amount: bigint, timestamp: bigint, status: bigint, evidenceHash: string, aiVerdict: string }],
      'view'
    >
    

    
    getEscrowDetails: TypedContractMethod<
      [_escrowId: BigNumberish, ],
      [Escrow.EscrowTransactionStructOutput],
      'view'
    >
    

    
    refundFunds: TypedContractMethod<
      [_escrowId: BigNumberish, _aiVerdict: string, ],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [_escrowId: BigNumberish, _aiVerdict: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_seller: AddressLike, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'dispute'): TypedContractMethod<
      [_escrowId: BigNumberish, _evidenceHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, string, string] & {buyer: string, seller: string, amount: bigint, timestamp: bigint, status: bigint, evidenceHash: string, aiVerdict: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrowDetails'): TypedContractMethod<
      [_escrowId: BigNumberish, ],
      [Escrow.EscrowTransactionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'refundFunds'): TypedContractMethod<
      [_escrowId: BigNumberish, _aiVerdict: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [_escrowId: BigNumberish, _aiVerdict: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowDisputed'): TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
getEvent(key: 'EscrowRefunded'): TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;

    filters: {
      
      'EscrowCreated(uint256,address,address,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowDisputed(uint256,string)': TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
      EscrowDisputed: TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
    

      'EscrowRefunded(uint256,string)': TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
      EscrowRefunded: TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
    

      'EscrowReleased(uint256,string)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    
    };
  }